/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { petsAdd } from "../funcs/petsAdd.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Pets extends ClientSDK {
  /**
   * Add a new pet to the store
   *
   * @remarks
   * Add a new pet to the store
   */
  async add(
    request: components.Pet,
    options?: RequestOptions,
  ): Promise<components.Pet> {
    return unwrapAsync(petsAdd(
      this,
      request,
      options,
    ));
  }
}
