/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usersLogin } from "../funcs/usersLogin.js";
import { usersUpdate } from "../funcs/usersUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Users extends ClientSDK {
  /**
   * Logs user into the system
   */
  async login(
    request: operations.LoginUserRequest,
    options?: RequestOptions,
  ): Promise<operations.LoginUserResponse> {
    return unwrapAsync(usersLogin(
      this,
      request,
      options,
    ));
  }

  /**
   * Update user
   *
   * @remarks
   * This can only be done by the logged in user.
   */
  async update(
    request: operations.UpdateUserRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(usersUpdate(
      this,
      request,
      options,
    ));
  }
}
