/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userCreate } from "../funcs/userCreate.js";
import { userCreateWithList } from "../funcs/userCreateWithList.js";
import { userDelete } from "../funcs/userDelete.js";
import { userGet } from "../funcs/userGet.js";
import { userLogout } from "../funcs/userLogout.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class User extends ClientSDK {
  /**
   * Create user
   *
   * @remarks
   * This can only be done by the logged in user.
   */
  async create(
    request?: components.User | undefined,
    options?: RequestOptions,
  ): Promise<components.User> {
    return unwrapAsync(userCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Creates list of users with given input array
   *
   * @remarks
   * Creates list of users with given input array
   */
  async createWithList(
    request?: Array<components.User> | undefined,
    options?: RequestOptions,
  ): Promise<components.User> {
    return unwrapAsync(userCreateWithList(
      this,
      request,
      options,
    ));
  }

  /**
   * Logs out current logged in user session
   */
  async logout(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(userLogout(
      this,
      options,
    ));
  }

  /**
   * Get user by user name
   */
  async get(
    request: operations.GetUserByNameRequest,
    options?: RequestOptions,
  ): Promise<components.User> {
    return unwrapAsync(userGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete user
   *
   * @remarks
   * This can only be done by the logged in user.
   */
  async delete(
    request: operations.DeleteUserRequest,
    options?: RequestOptions,
  ): Promise<components.User> {
    return unwrapAsync(userDelete(
      this,
      request,
      options,
    ));
  }
}
